# Generated by Django 3.2.13 on 2022-06-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_of_subscriber', models.EmailField(max_length=200, unique=True)),
                ('status', models.CharField(blank=True, choices=[('Unconfirmed', 'Unconfirmed'), ('Confirmed', 'Confirmed'), ('Unsubscribed', 'Unsubscribed')], default='Unconfirmed', max_length=64)),
                ('saving_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-saving_date',),
            },
        ),
    ]
